### ISSUE TITLE
Warnings and Notices

### ISSUE THREAD

**Issue by eurobank** [dftd/oscplugin-advcaptcha#4]
Some small (?) problems:

PHP Warning: Illegal string offset 'type' in /home/public_html/oc-content/plugins/zo_advancedcaptcha/classes/AdvancedCaptcha.php on line 59

PHP Notice: Uninitialized string offset: 0 in /home/public_html/oc-content/plugins/zo_advancedcaptcha/classes/AdvancedCaptcha.php on line 59

This seems to happen when numbers option is used.

**Comment by webmods-dev** [comment]
On which page/form does the issue happen. By "numbers option" you mean "Math" type?

**Comment by eurobank** [comment]
Yes, Math type, sorry wrong wording .....

**Comment by eurobank** [comment]
After switching to TEXT option, i get the very same issues. 

**So not a Math issue but a global one.**

**Comment by eurobank** [comment]
Any update in this?

**Comment by eurobank** [comment]
After 8 months i guess this is not gonna be fixed, so i'm closing it and remove the plugin.
